// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbE9PcQdPR6r3GiwpPWtPzUkKZ5IrSY8',
    appId: '1:880057154130:web:86469249ff1d882c3dbd8b',
    messagingSenderId: '880057154130',
    projectId: 'flutterfire-ui-11bda',
    authDomain: 'flutterfire-ui-11bda.firebaseapp.com',
    storageBucket: 'flutterfire-ui-11bda.appspot.com',
    measurementId: 'G-VJDCLBBP53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvhbrbKPv4DL_xgPzGsnGE8giKe0Sm1A',
    appId: '1:880057154130:android:07c0ebcc0eb386583dbd8b',
    messagingSenderId: '880057154130',
    projectId: 'flutterfire-ui-11bda',
    storageBucket: 'flutterfire-ui-11bda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaEHF9k48GjSSXNBeYPIWyLR_La5dgHc',
    appId: '1:880057154130:ios:46527fca93c3f5f23dbd8b',
    messagingSenderId: '880057154130',
    projectId: 'flutterfire-ui-11bda',
    storageBucket: 'flutterfire-ui-11bda.appspot.com',
    iosBundleId: 'com.example.authfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmaEHF9k48GjSSXNBeYPIWyLR_La5dgHc',
    appId: '1:880057154130:ios:46527fca93c3f5f23dbd8b',
    messagingSenderId: '880057154130',
    projectId: 'flutterfire-ui-11bda',
    storageBucket: 'flutterfire-ui-11bda.appspot.com',
    iosBundleId: 'com.example.authfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCbE9PcQdPR6r3GiwpPWtPzUkKZ5IrSY8',
    appId: '1:880057154130:web:a604c10c31d6d6e03dbd8b',
    messagingSenderId: '880057154130',
    projectId: 'flutterfire-ui-11bda',
    authDomain: 'flutterfire-ui-11bda.firebaseapp.com',
    storageBucket: 'flutterfire-ui-11bda.appspot.com',
    measurementId: 'G-47D8E74V84',
  );
}
